Use cached copy of assembly listing if no decode.asm.lst

diff --git a/co2do b/co2do
--- a/co2do
+++ b/co2do
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash
 # co2do.sh
 # by hackerb9, February 2026
 #
@@ -38,6 +38,9 @@
 #       * Prevent writing to bad parts of RAM.
 #         (E.g., POKE Q where Q<HIMEM or Q>=MAXRAM).
 #
+
+set +o errexit
+set +o pipefail
 
 function usage() {
     cat <<EOF
@@ -125,7 +128,7 @@ function emitmldecode() {
 	12080 POKE DC, Q-DX: 'Set length of DC$
 	12090 RETURN
 	EOF
-    dodo decode.asm.lst
+    dodo
 }
 
 function emitbasicdecode() {
@@ -166,14 +169,124 @@ emitnecvarptr() {
 }
 
 
+# XXX todo: update this from decode.asm.lst automatically.
+DECODEASMLST=$(cat <<EOF
+                        	;; Given a destination address and the varptr of a BASIC
+                        	;; string, copy the source string to the destination,
+                        	;; processing !-escapes by replacing each '!' with the
+                        	;; subsequent character with the high-bit flipped.
+
+                        	;; Calling is a two step process. First, the destination
+                        	;; address is sent from BASIC in HL by calling DCINIT.
+                        	;; Second, MAIN (= DCINIT+6) is called with the varptr of
+                        	;; the source string in HL.
+
+                        	;; The call to DCINIT also specifies a number in register A
+                        	;; from 0 to 255 to be subtracted from every byte. This allows
+                        	;; the coding to be more efficient by rotating the character
+                        	;; set.
+
+                        	;; Upon return, the length of the source string is modified to
+                        	;; reflect the actual number of characters written to the
+                        	;; destination address. The source string data is NOT changed.
+
+                        	;; Example usage from BASIC:
+                        	;;      10 DC=(DCINIT address after relocation)
+                        	;; 	15 A=(rotation offset or 0)
+                        	;;      20 Q=(destination buffer address)
+                        	;; 	30 READ P$: IF P$="EOD" THEN END
+                        	;;  	40 CALL DC, A, Q
+                        	;; 	50 CALL DC+6, 0, VARPTR(P$)
+                        	;; 	60 Q=Q+LEN(P$)
+                        	;; 	70 GOTO 30
+                        	;;
+                        	;; When appending multiple strings to the same buffer, the
+                        	;; destination address does not need to be updated each time.
+                        	;; The following is equivalent to the above code:
+
+                        	;;      10 DC=(DCINIT address after relocation)
+                        	;; 	15 A=(rotation offset or 0)
+                        	;;  	20 CALL DC, A, (destination buffer address)
+                        	;; 	30 READ P$: IF P$="EOD" THEN END
+                        	;; 	40 CALL DC+6, 0, VARPTR(P$)
+                        	;; 	50 GOTO 30
+
+0000                    	CPU 8085		; Build with asmx -w -e -l -b0 decode.asm
+
+0000                    	ORG 0			; The BASIC loader relocates this routine.
+0000                    DCINIT:	
+0000  32 2A00           	STA ROT			; Save A as Rotation Offset for charset
+0003  22 0700           	SHLD DEST		; Save HL in DEST as destination address.
+0006  C9                	RET
+
+0007  0000              DEST:	DW 0
+
+0009                    MAIN:	
+                        	;; HL starts as VARPTR(P$) where P$ is bang-encoded.
+0009  E5                	PUSH H
+000A  46                	MOV B, M		; B is length of input string
+000B  0E 00             	MVI C, 0		; C will be resulting length
+000D  23                	INX H
+000E  5E                	MOV E, M		; Load actual address of string into DE
+000F  23                	INX H
+0010  56                	MOV D, M
+0011  2A 0700           	LHLD DEST		; Restore HL from saved DEST
+0014  EB                	XCHG			; Now HL is P$'s actual address
+                        				; and DE is address of destination
+0015  78                	MOV A, B
+0016  A7                	ANA A
+0017  CA 3400           	JZ END			; Zero-length string?
+001A                    LOOP:	
+001A  7E                	MOV A, M		; Get next byte from source (*HL)
+001B  FE 21             	CPI '!'
+001D  C2 2800           	JNZ WRITE		; If not '!' just copy the character.
+0020  05                	DCR B
+0021  CA 3400           	JZ END			; Ignore escape char with no following char.
+0024  23                	INX H			; Char is '!' so get next char in A
+0025  7E                	MOV A, M
+0026  EE 80             	XRI 128			; Decode character by flipping bit 7
+0028                    WRITE:	
+0028  EB                	XCHG
+0029  D6                	DB D6h			; D6 is SUI instruction.
+002A  00                ROT:	DB 0			; Subtract this value from char.
+002B  77                	MOV M, A		; Copy the byte from *HL to *DE.
+002C  EB                	XCHG
+002D  23                	INX H
+002E  13                	INX D
+002F  0C                	INR C
+0030  05                	DCR B
+0031  C2 1A00           	JNZ LOOP
+0034                    END:	
+0034  EB                	XCHG			; Save DE in DEST so next call can skip DCINIT
+0035  22 0700           	SHLD DEST
+0038  EB                	XCHG			; Not needed, just being overly fastidious
+0039  E1                	POP H
+003A  71                	MOV M, C		; Write new length to BASIC string
+                        	
+003B  C9                	RET
+
+00000 Total Error(s)
+
+DCINIT             00000000    DEST               00000007    END                00000034
+LOOP               0000001A    MAIN               00000009    ROT                0000002A
+WRITE              00000028
+EOF
+)
+
 function dodo() {
     # dodo: DATA output decode.asm to .DO.
     # Given the filename of an assembly listing (from `asmx -l`), output
     # the bytes as decimal values separated by commas in a DATA statement.
     # Addresses that will need to be relocated are prefixed with -7.
     # End of data is signaled by -1.
+
+    # Use the cached copy in $DECODEASMLST, unless the file
+    # "decode.asm.lst" exists in the current directory,
+    if [[ -r "decode.asm.lst" ]]; then
+	DECODEASMLST=$(cat "decode.asm.lst")
+    fi
     echo -n "12500 DATA "
-    cat "$@" | parselst
+    echo "$DECODEASMLST" | parselst
     echo -1
     return
 }
@@ -255,9 +368,12 @@ outputfilter() {
     printf '\x1A'
 }
 
-
 main $(od -t u1 -v -An "$input") | $tandycharset | outputfilter > "$output"
 err=${PIPESTATUS[0]}
+if (( err != 0 )); then
+    echo "Exiting with error $err" >&2
+    exit $err
+fi
 
 if [[ $tandycharset == "cat" && -z $quiet ]]; then
     outnodo=${output##*/}
