Add 'RUN"COM:...' instructions for largish files
This is not done correctly as I don't know the exact way to calculate
when it will fail. Instead, as a heuristic, I'm just checking if
the TOP address is low enough that I've had problems in the past.

This does not take into account the amount of memory the BASIC loader
will need, nor does it consider string space or maxfiles.

diff --git a/co2do b/co2do
--- a/co2do
+++ b/co2do
@@ -63,7 +63,6 @@ function main() {
     emitbasicdecode
     printf "14000 '$input"
     emitdata "$@"
-    printf "\x1A"		# ^Z is EOF for Kyotronic Kin
     warnmem $TOP $LEN $EXE $#
     return			# Return result from warnmem
 }
@@ -109,6 +108,17 @@ function emitbasicdecode() {
 }
 
 
+declare -i ERRINVALIDCO=$((1<<0))
+declare -i ERRTOPINVALID=$((1<<1))
+declare -i ERRTOP8K=$((1<<2))
+declare -i ERRTOP8KDO=$((1<<3))
+declare -i ERRMAXRAMT200=$((1<<4))
+declare -i ERRMAXRAMNEC=$((1<<5))
+declare -i ERRMAXRAMKYO=$((1<<6))
+#declare -i ERR=$((1<<))
+#declare -i ERR=$((1<<))
+
+
 function warnmem() {
     # Print warnings given TOP, LEN, EXE, and size of the ML program
     local -i top=$1 len=$2 exe=$3 mlsize=$4
@@ -116,36 +126,37 @@ function warnmem() {
 
     # Sanity check
     if ((len != mlsize)); then
-	echo "Error: Not a valid .CO file. LEN=$len, but FILESIZE=$mlsize.">&2
-	err=1^err
+	printf "\nERROR:\n\tNot a valid .CO file. LEN=$len, but FILESIZE=$mlsize.\n\n">&2
+	err=1^ERRINVALIDCO
     fi
 
     # due to overhead, this program cannot convert some .CO files to BASIC.
     if ((top<32768)); then
-	echo "Warning: TOP ($top) is EXTREMELY low and likely invalid." >&2
-	err=err^2
+	printf "\nERROR:\n\tTOP ($top) < 32768, writing to Read-only Memory.\n\n" >&2
+	err=err^ERRTOPINVALID
     elif ((top<59555)); then
-	echo "Warning: TOP ($top) is very low and $output may not work on 8K machines." >&2
-	err=err^4
+	printf "Warning:\n\tTOP ($top) is very low. $output may not work on 8K machines.\n\n" >&2
+	err=err^ERRTOP8K
     elif ((top<61000)); then
 	cat <<-EOF >&2
 	Note: TOP ($top) is too low for 8K machines to fit both .DO and .BA.
 	To workaround, tokenize directly from a device instead of downloading.
 	For example, RUN "COM:98N1" or RUN "0:$output"
+
 	EOF
-	err=err^8
+	err=err^ERRTOP8KDO
     fi
 
     # Check if END exceeds MAXRAM
     if ((end>61104)); then
-	echo "Warning: END ($end) > 61104. $input will crash a Tandy 200!">&2
-	err=err^16
+	printf "\nWarning:\n\tEND ($end) > 61104. $input will crash a Tandy 200!\n\n">&2
+	err=err^ERRMAXRAMT200
     elif ((end>62336)); then
-	echo "Warning: END ($end) > 62336. $input will crash PC-8201/8300 and Tandy 200">&2
-	err=err^16
+	printf "\nWarning:\n\tEND ($end) > 62336. $input will crash PC-8201/8300 and Tandy 200\n\n">&2
+	err=err^ERRMAXRAMNEC
     elif ((end>62960)); then
-	echo "Warning: END ($end) > 62960. $input will crash all Model-T computers!!">&2
-	err=err^16
+	printf "\nError:\n\tEND ($end) > 62960. $input will crash *all* Model-T computers!!\n\n">&2
+	err=err^ERRMAXRAMKYO
     fi
 
     return $err
@@ -184,8 +195,29 @@ function warnmem() {
 	fi
     fi
 }
-main $(od -t u1 -v -An "$input") | $tandycharset > "$output"
+
+outputfilter() {
+    # Add carriage returns since NEC PC-8201 uses Mac (or DOS?) line endings.
+    # Append ^Z at end of file to signal receiving M100 that file is finished.
+    sed 's/$/\r/g'
+    printf '\x1A'
+}
+
+
+main $(od -t u1 -v -An "$input") | $tandycharset | outputfilter > "$output"
 err=${PIPESTATUS[0]}
+
+if (( err & ERRTOP8KDO )); then
+    cat <<-EOF
+	Use a serial connection to transfer $output to your Model-T
+	by using this BASIC command (pick the one for your machine):
+	    run "COM:88N1"	# Model 100, Tandy 102, Kyotronic 85, Olivetti M10
+	    run "COM:88N1ENN"	# Tandy 200
+	    run "COM:8N81XN" 	# NEC PC-8201/8300
+	On your host PC, send the file to serial port. For example:
+	    cat $output >/dev/ttyUSB0
+	EOF
+fi
 
 if (( err != 0 )); then
     exit $err
